import PropTypes from 'prop-types';

import ColorTemplate16PopupCenterWide from 'ui-component/ColorTemplate16PopupCenterWide';
import PageInstructionPopup from 'ui-component/PageInstructionPopup';
import PageInstructionButton from 'ui-component/PageInstructionButton';
import PageInstructionAudioTutorial from 'ui-component/PageInstructionAudioTutorial';
import {
  PAGE_INSTRUCTION_TOOLTIP_BG,
  PAGE_INSTRUCTION_TOOLTIP_TEXT
} from 'config/pageInstructionEnv';
import audioSelfReportSora from 'assets/sound/self_report_biography_instruction_Sora.m4a';
import audioSelfReportJessica from 'assets/sound/self_report_biography_instruction_Jessica.m4a';
import audioSelfReportMichael from 'assets/sound/self_report_biography_instruction_Michael.m4a';
import audioReceivedBioSora from 'assets/sound/received_bio_requests_instruction_Sora.m4a';
import audioReceivedBioJessica from 'assets/sound/received_bio_requests_instruction_Jessica.m4a';
import audioReceivedBioMichael from 'assets/sound/received_bio_requests_instruction_Michael.m4a';
import {
  SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_STEP,
  SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_TITLE
} from 'constants/selfReportBiographyInstructionText';
import {
  RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_STEP,
  RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_TITLE
} from 'constants/receivedBioRequestsInstructionText';

const SELF_REPORT_BIOGRAPHY_INSTRUCTION_AUDIO_BY_VOICE = {
  Sora: typeof audioSelfReportSora === 'string' ? audioSelfReportSora : audioSelfReportSora?.default || '',
  Jessica:
    typeof audioSelfReportJessica === 'string' ? audioSelfReportJessica : audioSelfReportJessica?.default || '',
  Michael:
    typeof audioSelfReportMichael === 'string' ? audioSelfReportMichael : audioSelfReportMichael?.default || ''
};

const RECEIVED_BIO_REQUESTS_INSTRUCTION_AUDIO_BY_VOICE = {
  Sora: typeof audioReceivedBioSora === 'string' ? audioReceivedBioSora : audioReceivedBioSora?.default || '',
  Jessica:
    typeof audioReceivedBioJessica === 'string' ? audioReceivedBioJessica : audioReceivedBioJessica?.default || '',
  Michael:
    typeof audioReceivedBioMichael === 'string' ? audioReceivedBioMichael : audioReceivedBioMichael?.default || ''
};

function PeerRequestsInstructionSection() {
  return (
    <>
      <PageInstructionPopup.SectionLabel>Peer Requests &amp; Absolute Control</PageInstructionPopup.SectionLabel>
      <PageInstructionPopup.BodyText>
        This final step happens dynamically when interacting with other members:
      </PageInstructionPopup.BodyText>
      <PageInstructionPopup.BodyText component="ul">
        <li>
          <strong>Strict Approval Workflow:</strong> If another member wants to view your biographical information, they must send a formal
          request to your inbox. You can review exactly who they are before granting access. No data is shared without your explicit consent.
        </li>
        <li>
          <strong>Verified Status Matching:</strong> Once you approve a request, the peer user can view the exact details you wrote on this
          page—accompanied by an official &ldquo;Info Matches&rdquo; or &ldquo;Info Not Matched&rdquo; status badge generated by our
          cross-check system.
        </li>
        <li>
          <strong>Instant Revocation:</strong> You remain in absolute control of your data. You can edit your biographical responses or
          instantly revoke access for any specific individual at any time in the future through your dashboard.
        </li>
      </PageInstructionPopup.BodyText>
    </>
  );
}

export function ReceivedBioRequestsInstructionBody() {
  return <PeerRequestsInstructionSection />;
}

export function SelfReportBiographyInstructionBody() {
  return (
    <>
      <ColorTemplate16PopupCenterWide.BodyText>
        This page is your toolkit for building a trustworthy, high-performing profile. Our goal is a safe matching environment where you
        remain in control of your privacy and are protected by FCRA standards.
      </ColorTemplate16PopupCenterWide.BodyText>
      <ColorTemplate16PopupCenterWide.SectionLabel>Four steps help you verify who you are:</ColorTemplate16PopupCenterWide.SectionLabel>
      <ColorTemplate16PopupCenterWide.BodyText component="ul">
        <li>
          <strong>Identity:</strong> Upload a photo ID and complete a live facial scan. That sensitive ID data is held only temporarily for
          the check, then deleted.
        </li>
        <li>
          <strong>Work:</strong> We send a 6-digit code to your work email so we can verify your company domain.
        </li>
        <li>
          <strong>Education:</strong> Order secure transcript services through parchment.com ($11 fee).
        </li>
        <li>
          <strong>LinkedIn:</strong> Link your account to verify your professional experience.
        </li>
      </ColorTemplate16PopupCenterWide.BodyText>
      <ColorTemplate16PopupCenterWide.SectionLabel>Keeping Your Information Secure</ColorTemplate16PopupCenterWide.SectionLabel>
      <ColorTemplate16PopupCenterWide.BodyText>
        We follow a Zero Database Exposure protocol: sensitive data such as your SSN is never handled by our main database. We adhere to
        FCRA rules so raw verification results stay protected and are used only to cross-check what you self-report here.
      </ColorTemplate16PopupCenterWide.BodyText>
      <ColorTemplate16PopupCenterWide.SectionLabel>Why a Complete Bio Matters!</ColorTemplate16PopupCenterWide.SectionLabel>
      <ColorTemplate16PopupCenterWide.BodyText>
        Watch the completion bar as you fill sections in. A higher completion percentage is an authenticity signal that makes it more likely
        others will connect with you.
      </ColorTemplate16PopupCenterWide.BodyText>
    </>
  );
}

export function SelfReportBiographyInstructionButton({ onClick }) {
  return <PageInstructionButton onClick={onClick} />;
}

export function ReceivedBioRequestsInstructionPopup({ open, onClose }) {
  return (
    <PageInstructionPopup open={open} onClose={onClose} closeOnBackdrop bodyTextAlignLeft centeredLeadLines={1}>
      <PageInstructionPopup.Body>
        <PageInstructionAudioTutorial
          active={open}
          audioByVoice={RECEIVED_BIO_REQUESTS_INSTRUCTION_AUDIO_BY_VOICE}
          title={RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_TITLE}
          contextStep={RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_STEP}
        />
        <ReceivedBioRequestsInstructionBody />
      </PageInstructionPopup.Body>
    </PageInstructionPopup>
  );
}

export function SelfReportBiographyInstructionPopup({ open, onClose }) {
  return (
    <ColorTemplate16PopupCenterWide
      open={open}
      onClose={onClose}
      closeOnBackdrop
      bodyTextAlignLeft
      centeredLeadLines={1}
      panelBg={PAGE_INSTRUCTION_TOOLTIP_BG}
      textColor={PAGE_INSTRUCTION_TOOLTIP_TEXT}
    >
      <ColorTemplate16PopupCenterWide.Body>
        <PageInstructionAudioTutorial
          active={open}
          audioByVoice={SELF_REPORT_BIOGRAPHY_INSTRUCTION_AUDIO_BY_VOICE}
          title={SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_TITLE}
          contextStep={SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_STEP}
        />
        <SelfReportBiographyInstructionBody />
      </ColorTemplate16PopupCenterWide.Body>
    </ColorTemplate16PopupCenterWide>
  );
}

SelfReportBiographyInstructionPopup.propTypes = {
  open: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired
};

ReceivedBioRequestsInstructionPopup.propTypes = {
  open: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired
};

SelfReportBiographyInstructionButton.propTypes = {
  onClick: PropTypes.func
};
