import PropTypes from 'prop-types';

import PageInstructionPopup from 'ui-component/PageInstructionPopup';
import PageInstructionButton from 'ui-component/PageInstructionButton';
import PageInstructionAudioTutorial from 'ui-component/PageInstructionAudioTutorial';
import audioSelfReportSora from 'assets/sound/self_report_biography_instruction_Sora.m4a';
import audioSelfReportJessica from 'assets/sound/self_report_biography_instruction_Jessica.m4a';
import audioSelfReportMichael from 'assets/sound/self_report_biography_instruction_Michael.m4a';
import audioReceivedBioSora from 'assets/sound/received_bio_requests_instruction_Sora.m4a';
import audioReceivedBioJessica from 'assets/sound/received_bio_requests_instruction_Jessica.m4a';
import audioReceivedBioMichael from 'assets/sound/received_bio_requests_instruction_Michael.m4a';
import {
  SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_STEP,
  SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_TITLE
} from 'constants/selfReportBiographyInstructionText';
import {
  RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_STEP,
  RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_TITLE
} from 'constants/receivedBioRequestsInstructionText';

const SELF_REPORT_BIOGRAPHY_INSTRUCTION_AUDIO_BY_VOICE = {
  Sora: typeof audioSelfReportSora === 'string' ? audioSelfReportSora : audioSelfReportSora?.default || '',
  Jessica:
    typeof audioSelfReportJessica === 'string' ? audioSelfReportJessica : audioSelfReportJessica?.default || '',
  Michael:
    typeof audioSelfReportMichael === 'string' ? audioSelfReportMichael : audioSelfReportMichael?.default || ''
};

const RECEIVED_BIO_REQUESTS_INSTRUCTION_AUDIO_BY_VOICE = {
  Sora: typeof audioReceivedBioSora === 'string' ? audioReceivedBioSora : audioReceivedBioSora?.default || '',
  Jessica:
    typeof audioReceivedBioJessica === 'string' ? audioReceivedBioJessica : audioReceivedBioJessica?.default || '',
  Michael:
    typeof audioReceivedBioMichael === 'string' ? audioReceivedBioMichael : audioReceivedBioMichael?.default || ''
};

function InstructionSection({ title, children }) {
  return (
    <>
      <PageInstructionPopup.SectionLabel>{title}</PageInstructionPopup.SectionLabel>
      {children}
    </>
  );
}

InstructionSection.propTypes = {
  title: PropTypes.string.isRequired,
  children: PropTypes.node.isRequired
};

function PeerRequestsInstructionSection() {
  return (
    <>
      <PageInstructionPopup.SectionLabel>Peer Requests &amp; Absolute Control</PageInstructionPopup.SectionLabel>
      <PageInstructionPopup.BodyText>
        This final step happens dynamically when interacting with other members:
      </PageInstructionPopup.BodyText>
      <PageInstructionPopup.BodyText component="ul">
        <li>
          <strong>Strict Approval Workflow:</strong> If another member wants to view your biographical information, they must send a formal
          request to your inbox. You can review exactly who they are before granting access. No data is shared without your explicit consent.
        </li>
        <li>
          <strong>Verified Status Matching:</strong> Once you approve a request, the peer user can view the exact details you wrote on this
          page—accompanied by an official &ldquo;Info Matches&rdquo; or &ldquo;Info Not Matched&rdquo; status badge generated by our
          cross-check system.
        </li>
        <li>
          <strong>Instant Revocation:</strong> You remain in absolute control of your data. You can edit your biographical responses or
          instantly revoke access for any specific individual at any time in the future through your dashboard.
        </li>
      </PageInstructionPopup.BodyText>
    </>
  );
}

export function ReceivedBioRequestsInstructionBody() {
  return <PeerRequestsInstructionSection />;
}

export function SelfReportBiographyInstructionBody() {
  return (
    <>
      <PageInstructionPopup.SectionTitle>How it Works: Secure Bio Verification</PageInstructionPopup.SectionTitle>
      <PageInstructionPopup.BodyText>
        Welcome to your Bio Verification control panel. To ensure maximum trust and safety while fully protecting your privacy, start with
        these two secure stages:
      </PageInstructionPopup.BodyText>
      <InstructionSection title="Step 1 - Complete Your Profile Bios">
        <PageInstructionPopup.BodyText>
          Fill out the three biographical sections below: Brief Bio, Full Bio, and Miscellaneous Optional Bio. You have total control over
          what details you choose to self-report and reveal on your profile.
        </PageInstructionPopup.BodyText>
      </InstructionSection>
      <InstructionSection title="Step 2 - Off-Site Secure Verification via 3rd-Party">
        <PageInstructionPopup.BodyText>
          Click the link to initiate your verification check with 3rd-Party, our reputable, nationwide third-party verification service.
        </PageInstructionPopup.BodyText>
        <PageInstructionPopup.BodyText component="ul">
          <li>
            <strong>Complete Privacy:</strong> 3rd-Party will contact you directly via email. You will enter your sensitive personal
            information (such as your SSN and Date of Birth) securely on 3rd-Party&apos;s platform only.
          </li>
          <li>
            <strong>Zero Database Exposure:</strong> Our server never sees, collects, or has access to your sensitive PII.
          </li>
          <li>
            <strong>FCRA Protection:</strong> Once 3rd-Party completes their assessment, they transmit raw verification data to our secure
            server. Due to strict federal FCRA regulations, we never share or expose this raw data to anyone. We only use it internally to
            cross-check against the profile information you filled out on this page.
          </li>
        </PageInstructionPopup.BodyText>
      </InstructionSection>
    </>
  );
}

export function SelfReportBiographyInstructionButton({ onClick }) {
  return <PageInstructionButton onClick={onClick} />;
}

export function ReceivedBioRequestsInstructionPopup({ open, onClose }) {
  return (
    <PageInstructionPopup open={open} onClose={onClose} closeOnBackdrop bodyTextAlignLeft centeredLeadLines={1}>
      <PageInstructionPopup.Body>
        <PageInstructionPopup.Title>{RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_TITLE}</PageInstructionPopup.Title>
        <PageInstructionAudioTutorial
          active={open}
          audioByVoice={RECEIVED_BIO_REQUESTS_INSTRUCTION_AUDIO_BY_VOICE}
          contextStep={RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_STEP}
        />
        <ReceivedBioRequestsInstructionBody />
      </PageInstructionPopup.Body>
    </PageInstructionPopup>
  );
}

export function SelfReportBiographyInstructionPopup({ open, onClose }) {
  return (
    <PageInstructionPopup open={open} onClose={onClose} closeOnBackdrop bodyTextAlignLeft centeredLeadLines={1}>
      <PageInstructionPopup.Body>
        <PageInstructionPopup.Title>{SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_TITLE}</PageInstructionPopup.Title>
        <PageInstructionAudioTutorial
          active={open}
          audioByVoice={SELF_REPORT_BIOGRAPHY_INSTRUCTION_AUDIO_BY_VOICE}
          contextStep={SELF_REPORT_BIOGRAPHY_INSTRUCTION_CONTEXT_STEP}
        />
        <SelfReportBiographyInstructionBody />
      </PageInstructionPopup.Body>
    </PageInstructionPopup>
  );
}

SelfReportBiographyInstructionPopup.propTypes = {
  open: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired
};

ReceivedBioRequestsInstructionPopup.propTypes = {
  open: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired
};

SelfReportBiographyInstructionButton.propTypes = {
  onClick: PropTypes.func
};
