/**
 * Received Bio Requests (/receivedBioRequests) page-instruction copy for TTS.
 * Keep bake script in sync:
 *   be/scripts/generateReceivedBioRequestsInstructionTutorialGemini.js
 */
export const RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_TITLE = 'Current Context Tutorial';
export const RECEIVED_BIO_REQUESTS_INSTRUCTION_CONTEXT_STEP =
  'You are in Received Biographical Requests page.';

/** Flat narration text (matches ReceivedBioRequestsInstructionBody). */
export const RECEIVED_BIO_REQUESTS_INSTRUCTION_SPEAK_TEXT = [
  'Peer Requests and Absolute Control.',
  'This final step happens dynamically when interacting with other members.',
  'Strict Approval Workflow: If another member wants to view your biographical information, they must send a formal request to your inbox. You can review exactly who they are before granting access. No data is shared without your explicit consent.',
  'Verified Status Matching: Once you approve a request, the peer user can view the exact details you wrote on this page—accompanied by an official Info Matches or Info Not Matched status badge generated by our cross-check system.',
  'Instant Revocation: You remain in absolute control of your data. You can edit your biographical responses or instantly revoke access for any specific individual at any time in the future through your dashboard.'
].join(' ');
