-- global.promotional_array — referral Post FB / Refer Email message bodies (text[]).
-- Run against Primary. Safe to re-run: replaces array on global row id=1.
-- Schema: helloworldjunktest (adjust if needed).

ALTER TABLE helloworldjunktest.global
  ADD COLUMN IF NOT EXISTS promotional_array text[] NOT NULL DEFAULT ARRAY[]::text[];

UPDATE helloworldjunktest.global
SET promotional_array = ARRAY[
  $p0$I'm so tired of the endless swiping and fake profiles on standard dating apps. I just found this new community that actually feels safe—everyone is verified by a 3rd party before joining. Plus, it has a social feed where you can post daily stories and pictures just like on here, making it way easier to see someone's real personality. Check it out if you're looking for something genuine!$p0$,
  $p1$Has anyone else tried this site yet? It's basically dating meets social media, but without the creeps. You can browse securely vetted profiles, chat, and you can even send real, physical flowers to someone to surprise them! It's such a cute concept for building actual romance. Definitely worth a look if you're single.$p1$,
  $p2$I decided to ditch the noise of the usual dating apps and found this awesome space. It's built for trusted romance with zero compromises on safety. You get to share your world through interactive posts and connect with people who are actually who they say they are. If you're looking for a friendly, vetted community, join me over here!$p2$,
  $p3$Honestly, I think I finally found a dating platform that gets it right. It goes way beyond just swiping—you can actually share your daily moments on a lively social feed, flirt in cozy private chats, and feel totally confident because every single person is vetted. It feels like a really secure haven for meeting new people. Let's connect on there!$p3$,
  $p4$Where transparency meets chemistry! I just signed up for this new dating site and I'm loving the vibe. It's like a fun social media feed but specifically for verified singles. You can share your photos, interact with posts, and just be yourself without worrying about who is behind the screen. Come join the community.$p4$,
  $p5$If you're looking to start real stories with actual verified dates, you have to check this out. I love that it's not just about a bio and a profile pic; you can post your favorite moments and see what others are up to day-to-day. It takes the pressure off and makes starting a conversation so much more natural. Join me here!$p5$,
  $p6$I've been using this new site and it's honestly the ultimate playground for romance. They do strict 3rd party vetting, so you have complete peace of mind while chatting. My favorite part is the photo sharing and the interactive posts—it makes cultivating a genuine connection so much easier. If you want a safe space to meet great singles, try the link.$p6$,
  $p7$Dating apps can be so exhausting, but I recently joined this new platform that totally changes the game. It's basically a hybrid between social media and dating. You can post your daily updates, comment, and flirt in a super secure, friendly environment. No more fake accounts! If you want to try something fresh, sign up below.$p7$,
  $p8$Just wanted to share this awesome new singles community I found! It's completely vetted, so you know you're talking to real people. The coolest part? You can interact through a lively social feed and even send real flower surprises right to someone's door to show you're interested. It's such a sweet, safe setup for finding love. Check it out.$p8$,
  $p9$Hey friends! If any of my single friends are looking for a better way to meet people, I highly recommend this site I just joined. It drops the endless swiping for actual interactive social posts, cozy chats, and a heavily vetted community so you can date with confidence. Let romance blossom the right way! Below is my invite link.$p9$,
  $p10$It's so hard to know who is real online these days, but I finally found a dating community that gets it right. Every single member goes through strict 3rd-party vetting. It's basically a safe haven where you can focus on connecting through a fun social feed instead of worrying about fakes. Come check it out.$p10$,
  $p11$Okay, this new dating platform I joined is actually so cute. It's not just swiping—you can scroll through a daily social feed of verified singles, and they even let you send real, physical flowers to someone you vibe with! Such a breath of fresh air. If you're single, you need to see this.$p11$,
  $p12$If anyone else is completely burnt out on regular dating apps, I highly recommend this new site. It feels more like hanging out on a social timeline where you can post pictures and see people's real personalities, plus everyone is vetted. It's a total game changer for meeting trusted singles. Join me.$p12$,
  $p13$I traded endless, mindless swiping for actual quality connections. This new community is completely vetted, meaning zero fake profiles. You get to interact naturally by liking and commenting on daily posts, making it so much easier to find genuine chemistry. Take a look.$p13$,
  $p14$Just popping on to share this amazing new dating space I found! It’s like all the fun parts of social media—posting your favorite moments and chatting—but everyone is a verified single looking for a real connection. It’s super safe and friendly. Below is my invite link.$p14$,
  $p15$Love the transparency of this new dating site! They use actual 3rd-party vetting so you know exactly who you're talking to. Plus, the interactive social feed makes breaking the ice feel completely natural and stress-free. If you want a better way to date, check this out.$p15$,
  $p16$Finally, a dating app that brings back actual romance! I love that you can bypass the superficial swiping, interact on a lively social feed, and even send real flower deliveries to get someone's attention. And the best part? Everyone is 100% verified. Join the club here.$p16$,
  $p17$I just joined this vetted singles community and the vibe is unmatched. It feels less like a stressful dating app and more like a fun social platform where you can safely meet new people, share your world, and flirt with confidence. Seriously, ditch the noise and try this.$p17$,
  $p18$Nothing beats the peace of mind knowing you're chatting with real, verified people. This new site I'm on combines strict safety checks with a super fun social media layout, so you can see daily stories and build a real connection before ever meeting up. Highly recommend.$p18$,
  $p19$Hey guys, if you're single and fed up with the usual apps, I just found this hidden gem. It's a secure, vetted community where you can share posts, flirt, and even send real flowers to matches. It's honestly the most refreshing dating experience I've had. Below is my link.$p19$
]::text[]
WHERE id = 1;

-- Verify: SELECT cardinality(promotional_array), promotional_array[1] FROM helloworldjunktest.global WHERE id = 1;
