import { getDBSchema } from '../../config/envConfig.js';
import pool from '../../db/connection.js';
import { resolveRequestsAppSchema } from './resolveRequestsAppSchema.js';

const POEM_THEME_TAG = 'vetted_friends';

const SEEDED_POEMS = [
  [
    'Vetted and verified, but waiting for you.',
    "To find a connection that's honest and true.",
    'Send a sweet bloom or a thoughtful "Hi,"',
    'You never know who might catch your eye.'
  ],
  [
    'Within this circle, every face is a friend,',
    'A new beginning on which you can depend.',
    'Let a flower speak what words cannot say,',
    "And brighten a special soul's world today."
  ],
  [
    'A gated garden of souls, trusted and fine,',
    'Where paths of two hearts begin to entwine.',
    'Plant a seed with a chat, let a flower be the sign,',
    "That you've found a connection truly divine."
  ],
  [
    'Hand-picked friends, curated for you,',
    'Authentic connections, honest and true.',
    'Reach out with a message to see where it leads,',
    'A flower is the simplest of romantic deeds.'
  ],
  [
    'In this quiet corner where trust is the key,',
    "Discover the person you're meant to meet.",
    'A flower for a smile, a message for a start,',
    'The shortest distance between two hearts.'
  ],
  [
    "No strangers here, only friends you've yet to meet,",
    'Making the journey of love a little more sweet.',
    'Send a bloom to show interest, or chat for a while,',
    "There's no better feeling than sparking a smile."
  ],
  [
    'A circle of trust, a gallery of hearts,',
    'This is where your next story starts.',
    'Share a word, let a conversation grow,',
    'Or send a flower to let a special someone know.'
  ],
  [
    'Real people, real hearts, and a space to belong,',
    'Where a simple "hello" can turn into a song.',
    'Strike up a chat or send a flower today,',
    'And let a new friendship lead the way.'
  ],
  [
    'Verified hearts in a peaceful place,',
    'Finding the beauty in every face.',
    'Whisper a message or send a bouquet,',
    'To brighten the world in a beautiful way.'
  ],
  [
    'Beyond the screen and the verified name,',
    'Lies a spark waiting to turn into a flame.',
    "Say hello through chat, or if you're feeling bold,",
    'Send a digital bloom and let a new bond unfold.'
  ],
  [
    'Carefully chosen, specifically for you,',
    'A circle of people, authentic and true.',
    'Let a flower speak softly or a conversation start,',
    "Open the door to a vetted friend's heart."
  ]
];

let poemsInitPromise = null;

async function resolvePoemsSchema() {
  try {
    return (await resolveRequestsAppSchema()) || getDBSchema() || 'public';
  } catch {
    return getDBSchema() || 'public';
  }
}

/** Table must exist (run be/db/addPoemsTable.sql). Seeds starter rows only (source `seed`). */
async function seedPoemsIfNeeded() {
  const schema = await resolvePoemsSchema();
  for (const lines of SEEDED_POEMS) {
    await pool.query(
      `INSERT INTO ${schema}.poems (theme_tag, line1, line2, line3, line4, source)
       VALUES ($1, $2, $3, $4, $5, 'seed')
       ON CONFLICT (theme_tag, line1, line2, line3, line4) DO NOTHING`,
      [POEM_THEME_TAG, lines[0], lines[1], lines[2], lines[3]]
    );
  }
  return schema;
}

async function getPoemsSchemaReady() {
  if (!poemsInitPromise) poemsInitPromise = seedPoemsIfNeeded();
  return poemsInitPromise;
}

async function pickRandomPoem(schema) {
  const result = await pool.query(
    `SELECT poem_id, line1, line2, line3, line4, source
     FROM ${schema}.poems
     WHERE theme_tag = $1
     ORDER BY RANDOM()
     LIMIT 1`,
    [POEM_THEME_TAG]
  );
  return result.rows[0] || null;
}

function jsonPoemRow(row) {
  return {
    poem_id: row.poem_id,
    lines: [row.line1, row.line2, row.line3, row.line4],
    source: row.source
  };
}

/**
 * Random row from `poems` for theme `vetted_friends`. No LLM — database only.
 * If no rows exist after seed, returns 503 so the UI does not substitute generated text.
 */
async function respondRandomPoemFromDb(schema, res) {
  const row = await pickRandomPoem(schema);
  if (row) {
    return res.json(jsonPoemRow(row));
  }
  return res.status(503).json({
    error: 'no_poems_in_database',
    message: 'No poems found for this theme. Run SQL seeds (be/db/seedPoemsVettedFriends.sql) or insert rows into poems.',
    hint: 'Poems must be stored in the database; they are not generated by this API.'
  });
}

/**
 * GET /api/requestedSingles/poem
 * Returns a random four-line poem from table `poems` (theme `vetted_friends`) only.
 */
export async function getRequestedSinglesPoem(req, res) {
  const me = Number(req.auth?.singles_id);
  if (!Number.isFinite(me) || me < 1) {
    return res.status(401).json({ error: 'Authentication required' });
  }
  try {
    const schema = await getPoemsSchemaReady();
    return respondRandomPoemFromDb(schema, res);
  } catch (error) {
    console.error('getRequestedSinglesPoem', error);
    if (error?.code === '42P01') {
      return res.status(503).json({
        error: 'Poems table is missing',
        hint: 'Create it with psql using be/db/addPoemsTable.sql (use your app schema; see comments in that file).'
      });
    }
    return res.status(500).json({ error: 'Failed to get poem' });
  }
}
